---
- hosts: staging
  gather_facts: True
  user: root
  sudo: True
  roles:
    - role: common
    - role: postgresql
    - role: nginx
    - role: django

  tasks:
    - include: roles/django/tasks/deploy.yml
